services:
  db:
    image: postgres:15
    container_name: nitbook_db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgAdmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin    

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: nitbook_api
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "4000:4000"
  
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: nitbook_app
    restart: unless-stopped
    depends_on:
      - api
    env_file:
      - ./app/.env
    ports:
      - "3000:3000"
    environment:
      - API_INTERNAL_URL=http://nitbook_api:4000
      - NEXT_PUBLIC_API_URL=https://api.gaggleniti.com

  librarians:
    build:
      context: ./librarians
      dockerfile: Dockerfile
    container_name: nitbook_librarians
    restart: unless-stopped
    depends_on:
      - api
    env_file:
      - ./librarians/.env
    ports:
      - "5000:5000" 
    environment:
      - API_INTERNAL_URL=http://nitbook_api:4000
      - NEXT_PUBLIC_API_URL=https://api.gaggleniti.com  

volumes:
  db_data:
  pgadmin_data:
