services:
  db:
    image: postgres:15
    container_name: nitbook_db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: nitbook_api
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - ./api/.env
    ports:
      - "4000:4000"
    command: >
      sh -c "
      npx prisma migrate deploy
      "

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: nitbook_app
    restart: unless-stopped
    depends_on:
      - api
    env_file:
      - ./app/.env
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000

volumes:
  db_data:
